 const data = {
    products: [
        {
            id: 1,
            name: " School bag",
            price: 50,
            image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTjnWdc8LQ0MpVDXnqjLtEqCXSBD3GudVyHZTGImZv&s",
        },
        {
            id: 2,
            name: "Television",
            price: 300,
            image: "https://www.shutterstock.com/image-photo/tv-flat-screen-lcd-plasma-260nw-314401364.jpg",
        },
        {
            id: 3,
            name: "Air conditioning",
            price: 350,
            image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQUHhqeVMyZDEpRnwXo34DulxR-1YyrSjFsUfqjZkvOPbSV_xicg_uSfIVr0LkFwOewfHvTPEcW4C4&usqp=CAc",
        },
        {
            id: 4,
            name: "Laptop",
            price: 250,
            image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQJA_QbJCCM72Gvfadnnk9PPu24ZJGe1JMQMYvLcPIlD-rEsHf0QYoCUesa566HqOQFF_uBCxdGRA4&usqp=CAc",
        },
        {
            id: 5,
            name: "Fridge",
            price: 150,
            image: "https://cdn.shopify.com/s/files/1/0523/8439/9556/products/image__42170_2048x2048.png?v=1633117556",
        },
        {
            id: 6,
            name: "Wrist watch",
            price: 50,
            image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRsfJd4j2B6zhW6KsdT1QubI6qw7lSVt_jd7XJYgCppuezs5-C0QSj5h_HqZP69MMoS6_P_6cIEIw&usqp=CAc",
        },
        {
            id: 7,
            name: " Wheel chair",
            price: 170,
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToIV_sYeiVoqqa9V_0-g48ZhmOOBtdeTvwjA&usqp=CAU",
        },
        {
            id: 8,
            name: "Home theater",
            price: 280,
            image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQIJNZTl2fy-03R_pHAFNFJEH_rVib3s39_50D0Gb5dz3W-Oi9_50aTmTNJE9o3g3lRMs1hOTZa4g&usqp=CAc",
        },
        {
            id: 9,
            name: "Iphone 14 pro ",
            price: 1500,
            image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQBgSTg7xB8KjVz7kRGbNnmuk98Wn4m0_Li6SJZbNZqKUcGVpclV2OGQPfzG1fioJTPRSGUv-M0bA&usqp=CAc",
            },
            {
             id: 10,
             name: "Bicycle",
             price: 30,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSny6CJV3XvImhx3MavagmcGbE7N_Tu2fM7Og7WNtKEig&s",
             },
             {
             id: 11,
             name: "Wheel barrow",
             price: 70,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROyumjdXyzSgzwAEjQwqki_-rW9mgh5RYnlI6sWiHj_g&s",
             },
             {
             id: 12,
             name: "Truck",
             price: 77000,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSESPqf8U-UqQClguODvtOw-tbo37vbN5FWSDRXqS7qgA&s",
             },
             {
            id: 13,
            name: "Playstation 5",
            price: 1300,
            image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSE_414kyUDVt_7NjzNmCRVx9ynoe530ByepIRAeTmg4appSVmsLkuBJIL6FJkFdSUkBO_hQsD-ew&usqp=CAc",
             },
             {
             id: 14,
             name: "Radio",
             price: 40,
             image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTsbFQmKa-KSvaEN6zKRXnB48FFdU0gcNToZsPH1fRfwtbBt4EXUxIg-SZUOsDW&usqp=CAc",
             },
             {
            id: 15,
            name: "Micro phone",
            price: 20,
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9FRImoH5YOGz4MpLgcGWnGtWzE3_SwCeAWg&usqp=CAU",
             },
             {
             id: 16,
             name: "Mens shoe",
             price: 200,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpKUHwKCRNippscZ5DQobkEfFr6UWCVrNJ4DCt1O99uVZeh8R6G23aauXQTuyx9iHNNks&usqp=CAU",
             },
             {
             id: 17,
             name: "Ladies shoe",
             price: 150,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwexJoRRrmIwBbDBjvdZvwzfKbwq81Fkn9dtnk7awVXWRhSN5JWsQ0dH_pxGhLivwRj_I&usqp=CAU",
             },
             {
             id: 18,
             name: " Glass table",
             price: 340,
             image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtrtmK-dIn7LMzCXDV57UZn2e5OsrncJdCOQ&usqp=CAU",
             },
             {
             id: 19,
             name: "Glass chair",
             price: 35,
             image: "https://www.ikea.com/us/en/images/products/tobias-chair-clear-chrome-plated__0727342_pe735614_s5.jpg",
              },
              {
             id: 20,
             name: "Wordrobe",
             price: 180,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEnoioyBTH3QLjD5vrf6lbBXEvL2iojJa7bg&usqp=CAU",
              },
              {
             id: 21,
             name: "wall clock",
             price: 35,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkfVvqCSgFPZDQU0O0C51gKLyXC-0bTc5KMg&usqp=CAU",
              },
              {
             id: 22,
             name: " Pot set",
             price: 45,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvhAQt3d_6ruEp94okUM8WgMjgpClx8UP1ow&usqp=CAU",
             },
             {
             id: 23,
             name: " Electric kettle",
             price: 55,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSsZdiJ86bU2gI2knqwqppxQjGvLa1Ajht9A&usqp=CAU",
              },
              {
             id: 24,
             name: "Generator",
             price: 160,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQtQF_RUBXJilWb0xUzk-_OHKo35rFszixkA&usqp=CAU",
             },
             {
             id: 25,
             name: "Bike",
             price: 3000,
             image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOP7ABEWjLgFyNCCUWTc8XOtOyllyWA6Jjag&usqp=CAU",
               },
            {
            id: 26,
            name: "Water bottle",
            price: 3,
            image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLHbboraKPHU_LqvtA4_gapHI53h2TZBdrkA&usqp=CAU",
              },
           {
           id: 27,
           name: "Ipod",
           price: 30,
           image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFPNuJMunPlzV9i1mUkSBZ0qq22tS57845OA&usqp=CAU",
           },
           {
           id: 28,
           name: "Standing fan",
           price: 40,
           image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_LH4LbKb0Y-xwGUBvF20BxUQnXgKdRnPb3A&usqp=CAU",
               },
           {
                 id: 29,
                 name: "CPU",
                 price: 200,
                 image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEIestETnJou2h6838ipSZM7hYoLge8rVbWROPPq8rQRcQmcQyeNi5KSaGA62DK7zXdw0&usqp=CAU",
                 },
                {
                id: 30,
                name: "Ladies Gown",
                price: 50,
                image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOGcLs-Bv89XZPWPGEAMcooYwK_-WknibAgQ&usqp=CAU",
              },
                
        ],
};
export default data;